# Generated by Django 4.2.23 on 2025-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="salons/", verbose_name="Фото салона"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="Фото услуги"
            ),
        ),
    ]
