# Generated by Django 4.2.23 on 2025-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_salon_image_service_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.RenameField(
            model_name="salon",
            old_name="image",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="image",
            new_name="photo",
        ),
    ]
