# Generated by Django 4.2.23 on 2025-06-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_category_rename_image_salon_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.category",
                verbose_name="Категория",
            ),
        ),
    ]
