# Generated by Django 4.2.23 on 2025-06-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="salon",
        ),
        migrations.AddField(
            model_name="specialist",
            name="salons",
            field=models.ManyToManyField(to="api.salon", verbose_name="Салоны"),
        ),
    ]
