# Generated by Django 4.2.23 on 2025-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_specialist_salon_specialist_salons'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='experience_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж (мес.)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='bio',
            field=models.TextField(max_length=700, verbose_name='Специальность'),
        ),
    ]
