# Generated by Django 4.2.23 on 2025-06-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_specialist_experience_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='bio',
            field=models.TextField(blank=True, max_length=700, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='salons',
            field=models.ManyToManyField(blank=True, to='api.salon', verbose_name='Салоны'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Занято')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialist')),
            ],
            options={
                'verbose_name': 'Слот времени',
                'verbose_name_plural': 'Слоты времени',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time', 'specialist', 'salon')},
            },
        ),
    ]
