# Generated by Django 4.2.23 on 2025-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_specialist_bio_alter_specialist_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="lat",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AddField(
            model_name="salon",
            name="lon",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
    ]
